#!/bin/bash
cd SUM_CMS
docker-compose up -d --build
docker-compose run --rm php composer install
docker-compose run --rm php cp .env.example .env
docker-compose run --rm php php artisan key:generate
docker-compose run --rm php chmod 777 -R storage bootstrap